### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by mlcdf** [notwaldorf/mojibrag#15] opened 2016-10-13 19:39 UTC
I have this weird layout issue on Chromium 52 (on a Ubuntu based distro) that blocks my click and prevents me from selecting the input fields & buttons (via the mouse).

![screenshot from 2016-10-13 21 22 17](https://cloud.githubusercontent.com/assets/9364931/19363667/ae0133d6-918b-11e6-9654-b09ea5c92d7c.png)

![screenshot from 2016-10-13 21 22 41](https://cloud.githubusercontent.com/assets/9364931/19363668/ae0b82a0-918b-11e6-977c-aa3364c8cd87.png)

It looks like it's the highlighted div (in orange) that blocks the clicks since when I click on "Create channel", the "Create channel" card appears, the div is slided down, and the top input field is now selectable.

**Comment by mlcdf** [comment] 2016-10-13 19:40
2 minutes to late :(

https://github.com/notwaldorf/mojibrag/issues/14

**Comment by notwaldorf** [comment] 2016-10-13 20:07
Closing as a dupe of 14 (so I can only comment in one place)

**Closed by notwaldorf** 2016-10-13 20:07 UTC
